#!/usr/bin/env bash

# Check if pip3 is installed
if ! command -v pip3 &> /dev/null; then
    echo "pip3 command not found. Installing python3-pip..."
    sudo apt-get update
    sudo apt-get install -y python3-pip
fi

# Uninstall Fabric
echo "Uninstalling Fabric..."
pip3 uninstall -y Fabric

# Install required libraries and packages
echo "Installing required libraries and packages..."
sudo apt-get update
sudo apt-get install -y libffi-dev libssl-dev build-essential python3.4-dev libpython3-dev

# Install required Python packages
echo "Installing required Python packages..."
pip3 install pyparsing appdirs
pip3 install setuptools==40.1.0
pip3 install cryptography==2.8
pip3 install bcrypt==3.1.7
pip3 install PyNaCl==1.3.0
pip3 install Fabric3==1.14.post1

# Install Fabric using apt
echo "Installing Fabric using apt..."
sudo apt-get install -y fabric

# Verify Fabric installation
fabric_version=$(fab --version)
if [[ -n "$fabric_version" ]]; then
    echo "Fabric installation completed."
    echo "Fabric version: $fabric_version"
else
    echo "Fabric installation failed."
fi
